PRODUCTOS_AGRO_CATALOGO = [
    {"producto_id": "1018", "producto_nombre": "Aceituna botija", "categoria": "fruta", "aliases": ["aceituna botija", "aceituna", "aceitunas"]},
    {"producto_id": "0202", "producto_nombre": "Aji fresco", "categoria": "hortaliza", "aliases": ["aji fresco", "aji"]},
    {"producto_id": "0203", "producto_nombre": "Aji seco", "categoria": "hortaliza", "aliases": ["aji seco"]},
    {"producto_id": "0204", "producto_nombre": "Ajo", "categoria": "hortaliza", "aliases": ["ajo", "ajos"]},
    {"producto_id": "0206", "producto_nombre": "Alcachofa", "categoria": "hortaliza", "aliases": ["alcachofa", "alcachofas"]},
    {"producto_id": "0207", "producto_nombre": "Apio", "categoria": "hortaliza", "aliases": ["apio"]},
    {"producto_id": "0401", "producto_nombre": "Arroz", "categoria": "cereal", "aliases": ["arroz"]},
    {"producto_id": "0301", "producto_nombre": "Arveja grano verde", "categoria": "legumbre", "aliases": ["arveja grano verde", "arveja verde", "arveja"]},
    {"producto_id": "0640", "producto_nombre": "Bayas", "categoria": "fruta", "aliases": ["bayas", "berry", "berries"]},
    {"producto_id": "0209", "producto_nombre": "Beterraga", "categoria": "hortaliza", "aliases": ["beterraga"]},
    {"producto_id": "0902", "producto_nombre": "Cafe", "categoria": "cultivo", "aliases": ["cafe"]},
    {"producto_id": "0101", "producto_nombre": "Camote", "categoria": "tuberculo", "aliases": ["camote", "camotes"]},
    {"producto_id": "0212", "producto_nombre": "Cebolla", "categoria": "hortaliza", "aliases": ["cebolla", "cebollas"]},
    {"producto_id": "0641", "producto_nombre": "Cerezas", "categoria": "fruta", "aliases": ["cereza", "cerezas"]},
    {"producto_id": "0603", "producto_nombre": "Chirimoya", "categoria": "fruta", "aliases": ["chirimoya", "chirimoyas"]},
    {"producto_id": "0403", "producto_nombre": "Choclo", "categoria": "cereal", "aliases": ["choclo"]},
    {"producto_id": "0604", "producto_nombre": "Ciruela", "categoria": "fruta", "aliases": ["ciruela", "ciruelas"]},
    {"producto_id": "0215", "producto_nombre": "Culantro", "categoria": "hortaliza", "aliases": ["culantro", "cilantro"]},
    {"producto_id": "0216", "producto_nombre": "Esparrago", "categoria": "hortaliza", "aliases": ["esparrago", "esparragos"]},
    {"producto_id": "0217", "producto_nombre": "Espinaca", "categoria": "hortaliza", "aliases": ["espinaca"]},
    {"producto_id": "0607", "producto_nombre": "Fresa", "categoria": "fruta", "aliases": ["fresa", "fresas", "frutilla", "frutillas"]},
    {"producto_id": "0501", "producto_nombre": "Frijol grano seco", "categoria": "legumbre", "aliases": ["frijol grano seco", "frijol seco", "frijol", "frijoles"]},
    {"producto_id": "0302", "producto_nombre": "Frijol grano verde", "categoria": "legumbre", "aliases": ["frijol grano verde", "frijol verde"]},
    {"producto_id": "0502", "producto_nombre": "Garbanzo grano seco", "categoria": "legumbre", "aliases": ["garbanzo", "garbanzos"]},
    {"producto_id": "0608", "producto_nombre": "Granadilla", "categoria": "fruta", "aliases": ["granadilla", "granadillas"]},
    {"producto_id": "0609", "producto_nombre": "Guanabana", "categoria": "fruta", "aliases": ["guanabana"]},
    {"producto_id": "0303", "producto_nombre": "Haba grano verde", "categoria": "legumbre", "aliases": ["haba grano verde", "haba verde", "haba", "habas"]},
    {"producto_id": "0218", "producto_nombre": "Hortalizas chinas", "categoria": "hortaliza", "aliases": ["hortalizas chinas"]},
    {"producto_id": "0220", "producto_nombre": "Lechuga", "categoria": "hortaliza", "aliases": ["lechuga"]},
    {"producto_id": "0504", "producto_nombre": "Lenteja grano seco", "categoria": "legumbre", "aliases": ["lenteja", "lentejas"]},
    {"producto_id": "0611", "producto_nombre": "Limon", "categoria": "fruta", "aliases": ["limon", "limones"]},
    {"producto_id": "0106", "producto_nombre": "Maca", "categoria": "tuberculo", "aliases": ["maca"]},
    {"producto_id": "0404", "producto_nombre": "Maiz seco", "categoria": "cereal", "aliases": ["maiz", "maiz seco"]},
    {"producto_id": "0614", "producto_nombre": "Mandarina", "categoria": "fruta", "aliases": ["mandarina", "mandarinas"]},
    {"producto_id": "0615", "producto_nombre": "Mango", "categoria": "fruta", "aliases": ["mango", "mangos"]},
    {"producto_id": "0617", "producto_nombre": "Manzana", "categoria": "fruta", "aliases": ["manzana", "manzanas"]},
    {"producto_id": "0618", "producto_nombre": "Maracuya", "categoria": "fruta", "aliases": ["maracuya"]},
    {"producto_id": "0107", "producto_nombre": "Mashua", "categoria": "tuberculo", "aliases": ["mashua"]},
    {"producto_id": "0620", "producto_nombre": "Melocoton", "categoria": "fruta", "aliases": ["melocoton"]},
    {"producto_id": "0619", "producto_nombre": "Melon", "categoria": "fruta", "aliases": ["melon"]},
    {"producto_id": "0621", "producto_nombre": "Membrillo", "categoria": "fruta", "aliases": ["membrillo", "membrillos"]},
    {"producto_id": "0622", "producto_nombre": "Naranja", "categoria": "fruta", "aliases": ["naranja", "naranjas"]},
    {"producto_id": "0102", "producto_nombre": "Olluco", "categoria": "tuberculo", "aliases": ["olluco"]},
    {"producto_id": "0506", "producto_nombre": "Pallar grano seco", "categoria": "legumbre", "aliases": ["pallar grano seco", "pallar seco", "pallar", "pallares"]},
    {"producto_id": "0305", "producto_nombre": "Pallar grano verde", "categoria": "legumbre", "aliases": ["pallar grano verde", "pallar verde"]},
    {"producto_id": "0626", "producto_nombre": "Palta", "categoria": "fruta", "aliases": ["palta", "paltas", "aguacate", "aguacates"]},
    {"producto_id": "0104", "producto_nombre": "Papa", "categoria": "tuberculo", "aliases": ["papa", "papas"]},
    {"producto_id": "0627", "producto_nombre": "Papaya", "categoria": "fruta", "aliases": ["papaya", "papayas"]},
    {"producto_id": "0630", "producto_nombre": "Pepino", "categoria": "hortaliza", "aliases": ["pepino", "pepinos"]},
    {"producto_id": "0224", "producto_nombre": "Pimiento fresco", "categoria": "hortaliza", "aliases": ["pimiento fresco", "pimiento", "pimientos"]},
    {"producto_id": "0628", "producto_nombre": "Pina", "categoria": "fruta", "aliases": ["pina", "pinas"]},
    {"producto_id": "0629", "producto_nombre": "Platano", "categoria": "fruta", "aliases": ["platano", "platanos", "banano", "banana"]},
    {"producto_id": "0405", "producto_nombre": "Quinua", "categoria": "cereal", "aliases": ["quinua", "quinoa"]},
    {"producto_id": "0633", "producto_nombre": "Sandia", "categoria": "fruta", "aliases": ["sandia"]},
    {"producto_id": "0306", "producto_nombre": "Tarhui", "categoria": "legumbre", "aliases": ["tarhui", "chocho"]},
    {"producto_id": "0228", "producto_nombre": "Tomate", "categoria": "hortaliza", "aliases": ["tomate", "tomates"]},
    {"producto_id": "0636", "producto_nombre": "Tuna", "categoria": "fruta", "aliases": ["tuna", "tunas"]},
    {"producto_id": "0637", "producto_nombre": "Uva", "categoria": "fruta", "aliases": ["uva", "uvas"]},
    {"producto_id": "0229", "producto_nombre": "Vainita", "categoria": "hortaliza", "aliases": ["vainita", "vainitas"]},
    {"producto_id": "0105", "producto_nombre": "Yuca", "categoria": "tuberculo", "aliases": ["yuca"]},
    {"producto_id": "0230", "producto_nombre": "Zanahoria", "categoria": "hortaliza", "aliases": ["zanahoria", "zanahorias"]},
    {"producto_id": "0231", "producto_nombre": "Zapallo", "categoria": "hortaliza", "aliases": ["zapallo", "zapallos"]},
]

PRODUCTOS_AGRO_EXTRA = [
    {"producto_id": "9001", "producto_nombre": "Paprika", "categoria": "hortaliza", "aliases": ["paprika", "aji paprika", "aji panca", "pimiento seco"]},
    {"producto_id": "9002", "producto_nombre": "Tara", "categoria": "cultivo", "aliases": ["tara", "tara powder", "tara gum"]},
    {"producto_id": "9003", "producto_nombre": "Higo", "categoria": "fruta", "aliases": ["higo", "higos"]},
    {"producto_id": "9004", "producto_nombre": "Aguaymanto", "categoria": "fruta", "aliases": ["aguaymanto", "golden berry"]},
    {"producto_id": "9005", "producto_nombre": "Chia", "categoria": "cereal", "aliases": ["chia"]},
    {"producto_id": "9006", "producto_nombre": "Achiote", "categoria": "cultivo", "aliases": ["achiote"]},
    {"producto_id": "9007", "producto_nombre": "Jengibre", "categoria": "cultivo", "aliases": ["jengibre", "ginger", "kion"]},
    {"producto_id": "9008", "producto_nombre": "Cacao", "categoria": "cultivo", "aliases": ["cacao", "cocoa"]},
    {"producto_id": "9009", "producto_nombre": "Arandano", "categoria": "fruta", "aliases": ["arandano", "arandanos", "blueberry", "blueberries"]},
    {"producto_id": "9010", "producto_nombre": "Granada", "categoria": "fruta", "aliases": ["granada", "granadas", "arilos de granada"]},
]

AGRO_HS_CHAPTERS = {
    "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "17", "18", "20",
}

PRODUCT_ALLOWED_PREFIXES = {
    "0637": ["080610"],
    "0626": ["080440"],
    "9009": ["081040"],
    "0615": ["080450"],
    "9010": ["0810909"],
    "0216": ["070920"],
    "0629": ["080390", "080310"],
    "0611": ["080550"],
    "0614": ["080521", "080529"],
    "0628": ["080430"],
    "0212": ["070310"],
    "9003": ["080420"],
    "0622": ["080510"],
    "0608": ["0810901"],
    "9004": ["0810905"],
    "0636": ["0810909"],
    "0618": ["0810901"],
    "0633": ["080711"],
    "0104": ["070190"],
    "0220": ["070511", "070519"],
    "0204": ["070320"],
    "0202": ["070960"],
    "0231": ["070993"],
    "0603": ["0810902"],
    "0403": ["070999"],
}

EXCLUSION_KEYWORDS = [
    "pescado",
    "harina de pescado",
    "aceite crudo de pescado",
    "aceite de pescado",
    "langostino",
    "camaron",
    "gamba",
    "calamar",
    "pulpo",
    "molusco",
    "crustaceo",
    "carne",
    "embutido",
    "congelado",
    "congelada",
    "congelados",
    "congeladas",
    "procesado",
    "procesada",
    "jugo",
    "pulpa",
    "conserva",
    "bebida",
    "tapa",
    "sardina",
    "semilla",
    "hibrida",
    "planta",
    "in vitro",
    "enlatado",
    "enlatados",
    "pasta",
    "salsa",
]
