PRODUCTOS_AGRICOLAS_PRIORITARIOS = [
    {"codigo": "1018", "nombre": "Aceituna botija", "categoria": "fruta"},
    {"codigo": "0202", "nombre": "Aji fresco", "categoria": "hortaliza"},
    {"codigo": "0203", "nombre": "Aji seco", "categoria": "hortaliza"},
    {"codigo": "0204", "nombre": "Ajo", "categoria": "hortaliza"},
    {"codigo": "0206", "nombre": "Alcachofa", "categoria": "hortaliza"},
    {"codigo": "0207", "nombre": "Apio", "categoria": "hortaliza"},
    {"codigo": "0401", "nombre": "Arroz", "categoria": "cereal"},
    {"codigo": "0301", "nombre": "Arveja grano verde", "categoria": "legumbre"},
    {"codigo": "0640", "nombre": "Bayas", "categoria": "fruta"},
    {"codigo": "0209", "nombre": "Beterraga", "categoria": "hortaliza"},
    {"codigo": "0902", "nombre": "Cafe", "categoria": "cultivo"},
    {"codigo": "0101", "nombre": "Camote", "categoria": "tuberculo"},
    {"codigo": "0212", "nombre": "Cebolla", "categoria": "hortaliza"},
    {"codigo": "0641", "nombre": "Cerezas", "categoria": "fruta"},
    {"codigo": "0603", "nombre": "Chirimoya", "categoria": "fruta"},
    {"codigo": "0403", "nombre": "Choclo", "categoria": "cereal"},
    {"codigo": "0604", "nombre": "Ciruela", "categoria": "fruta"},
    {"codigo": "0215", "nombre": "Culantro", "categoria": "hortaliza"},
    {"codigo": "0216", "nombre": "Esparrago", "categoria": "hortaliza"},
    {"codigo": "0217", "nombre": "Espinaca", "categoria": "hortaliza"},
    {"codigo": "0607", "nombre": "Fresa", "categoria": "fruta"},
    {"codigo": "0501", "nombre": "Frijol grano seco", "categoria": "legumbre"},
    {"codigo": "0302", "nombre": "Frijol grano verde", "categoria": "legumbre"},
    {"codigo": "0502", "nombre": "Garbanzo grano seco", "categoria": "legumbre"},
    {"codigo": "0608", "nombre": "Granadilla", "categoria": "fruta"},
    {"codigo": "0609", "nombre": "Guanabana", "categoria": "fruta"},
    {"codigo": "0303", "nombre": "Haba grano verde", "categoria": "legumbre"},
    {"codigo": "0218", "nombre": "Hortalizas chinas", "categoria": "hortaliza"},
    {"codigo": "0220", "nombre": "Lechuga", "categoria": "hortaliza"},
    {"codigo": "0504", "nombre": "Lenteja grano seco", "categoria": "legumbre"},
    {"codigo": "0611", "nombre": "Limon", "categoria": "fruta"},
    {"codigo": "0106", "nombre": "Maca", "categoria": "tuberculo"},
    {"codigo": "0404", "nombre": "Maiz seco", "categoria": "cereal"},
    {"codigo": "0614", "nombre": "Mandarina", "categoria": "fruta"},
    {"codigo": "0615", "nombre": "Mango", "categoria": "fruta"},
    {"codigo": "0617", "nombre": "Manzana", "categoria": "fruta"},
    {"codigo": "0618", "nombre": "Maracuya", "categoria": "fruta"},
    {"codigo": "0107", "nombre": "Mashua", "categoria": "tuberculo"},
    {"codigo": "0620", "nombre": "Melocoton", "categoria": "fruta"},
    {"codigo": "0619", "nombre": "Melon", "categoria": "fruta"},
    {"codigo": "0621", "nombre": "Membrillo", "categoria": "fruta"},
    {"codigo": "0622", "nombre": "Naranja", "categoria": "fruta"},
    {"codigo": "0102", "nombre": "Olluco", "categoria": "tuberculo"},
    {"codigo": "0506", "nombre": "Pallar grano seco", "categoria": "legumbre"},
    {"codigo": "0305", "nombre": "Pallar grano verde", "categoria": "legumbre"},
    {"codigo": "0626", "nombre": "Palta", "categoria": "fruta"},
    {"codigo": "0104", "nombre": "Papa", "categoria": "tuberculo"},
    {"codigo": "0627", "nombre": "Papaya", "categoria": "fruta"},
    {"codigo": "0630", "nombre": "Pepino", "categoria": "hortaliza"},
    {"codigo": "0224", "nombre": "Pimiento fresco", "categoria": "hortaliza"},
    {"codigo": "0628", "nombre": "Pina", "categoria": "fruta"},
    {"codigo": "0629", "nombre": "Platano", "categoria": "fruta"},
    {"codigo": "0405", "nombre": "Quinua", "categoria": "cereal"},
    {"codigo": "0633", "nombre": "Sandia", "categoria": "fruta"},
    {"codigo": "0306", "nombre": "Tarhui", "categoria": "legumbre"},
    {"codigo": "0228", "nombre": "Tomate", "categoria": "hortaliza"},
    {"codigo": "0636", "nombre": "Tuna", "categoria": "fruta"},
    {"codigo": "0637", "nombre": "Uva", "categoria": "fruta"},
    {"codigo": "0229", "nombre": "Vainita", "categoria": "hortaliza"},
    {"codigo": "0105", "nombre": "Yuca", "categoria": "tuberculo"},
    {"codigo": "0230", "nombre": "Zanahoria", "categoria": "hortaliza"},
    {"codigo": "0231", "nombre": "Zapallo", "categoria": "hortaliza"},
]

